FROM golang:1.14-stretch as base

WORKDIR /go/src/github.com/codesenberg/bombardier

RUN git clone https://github.com/codesenberg/bombardier .

RUN go build -ldflags '-extldflags "-fno-PIC -static"' -buildmode pie -tags 'osusergo netgo static_build' -o /bin/bombardier .

FROM gcr.io/distroless/static:nonroot
COPY --from=base /bin/bombardier /bin/bombardier

ENTRYPOINT ["/bin/bombardier"]
